window.__NUXT__ = (function (
  a,
  b,
  c,
  d,
  e,
  f,
  g,
  h,
  i,
  j,
  k,
  l,
  m,
  n,
  o,
  p,
  q
) {
  return {
    layout: 'default',
    data: [
      {
        sites: [
          {
            id: 32,
            companyId: c,
            name: k,
            domain: k,
            path: f,
            email: e,
            branch: g,
            edition: 2,
            createdAt: '2020-11-26T04:59:22.919Z',
            updatedAt: h,
            deleteAt: a,
            deleteFlag: b,
            runningStatus: b,
            revisionStatus: b,
            lbDNSName: a,
            company: {
              id: c,
              agencyId: a,
              name: i,
              email: j,
              tel: a,
              deleteFlag: b,
              createdAt: d,
              updatedAt: d,
              deletedAt: a,
            },
          },
          {
            id: 31,
            companyId: c,
            name: l,
            domain: l,
            path: f,
            email: e,
            branch: g,
            edition: c,
            createdAt: '2020-11-26T04:56:04.655Z',
            updatedAt: h,
            deleteAt: a,
            deleteFlag: b,
            runningStatus: b,
            revisionStatus: b,
            lbDNSName: a,
            company: {
              id: c,
              agencyId: a,
              name: i,
              email: j,
              tel: a,
              deleteFlag: b,
              createdAt: d,
              updatedAt: d,
              deletedAt: a,
            },
          },
          {
            id: 30,
            companyId: c,
            name: m,
            domain: m,
            path: f,
            email: e,
            branch: g,
            edition: b,
            createdAt: '2020-11-26T04:52:31.907Z',
            updatedAt: h,
            deleteAt: a,
            deleteFlag: b,
            runningStatus: b,
            revisionStatus: b,
            lbDNSName: a,
            company: {
              id: c,
              agencyId: a,
              name: i,
              email: j,
              tel: a,
              deleteFlag: b,
              createdAt: d,
              updatedAt: d,
              deletedAt: a,
            },
          },
        ],
        total: 3,
      },
    ],
    fetch: [],
    error: a,
    state: {
      app: {
        sidebar: { opened: false },
        device: c,
        size: 'medium',
        env: {
          rootUrl: n,
          rootDomain: n,
          baseApiUrl: o,
          baseSsrApiUrl: o,
          cronTime: 10000,
        },
      },
      user: {
        authenticated: p,
        token:
          'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsIm5hbWUiOiJTdXBlciBBZG1pbiIsImlhdCI6MTYwOTgxNTkxNiwiZXhwIjoxNjEwMDc1MTE2fQ.7VryCvNFbPfkqwg8RQp3lCFulxc9JaNU1e8GNUCiz-A',
        info: { id: c, name: q, email: e, agencyId: a, role: c },
        tokenPayload: {
          id: c,
          email: e,
          name: q,
          iat: 1609815916,
          exp: 1610075116,
        },
      },
    },
    serverRendered: p,
    routePath: '\u002Fsite\u002Flist',
  }
})(
  null,
  0,
  1,
  '2020-10-09T12:14:03.564Z',
  'admin@example.com',
  '\u002F',
  'release\u002Fnext-ex',
  '2021-01-04T20:50:00.000Z',
  'てすと',
  'noguchi@rs-lab.jp',
  'ex.toremasse-trial3-rsonly.com',
  'next.toremasse-trial3-rsonly.com',
  'trial.toremasse-trial3-rsonly.com',
  '',
  'https:\u002F\u002Fcpapi.toremasse-trial3-rsonly.com\u002F',
  true,
  'Super Admin'
)
